### ISSUE TITLE
_path vs. @path

### ISSUE THREAD

**Issue by philrz** [corelight/ecs-mapping#1]
I'm happy to say that I was able to successfully ingest some JSON events from my open source Zeek using this code in this repo. It did take just a bit of hacking, though, so I'm opening a few issues on some of the minor snags I worked around in the event anyone wants to make enhancements so future generations won't need to hack quite as much.

I happen to use Zeek events output by https://github.com/corelight/json-streaming-logs as the format I ultimately send toward Elasticsearch for ingest+index. One of its default behaviors is that the Zeek "path" field key is `_path`, whereas the pipeline code [here](https://github.com/corelight/ecs-mapping/blob/8a05691f329bacb84cf59207bdfdf31e962fae23/automatic_install/corelight_general_pipeline#L5-L8) expects `@path`. Until I caught this, I briefly scratched my head and wondering why all my events seemed to be completely missing the pipeline and none of the ECS field names were appearing.

I'm assuming a Corelight sensor sends it as `@path` when it knows it's sending to Elasticsearch, since I'm more accustomed to seeing meta fields with leading `@` in that universe. But it might be worth adding some logic to catch the `_path` variant as well in this rename step.

**Comment by brianddye** [comment]
Phil - thanks for highlighting this! The @path setting was fixed in a commit this morning.
