### ISSUE TITLE
Is this mapping a superset of official ECS?

### ISSUE THREAD

**Issue by mavam** [corelight/ecs-mapping#18]
I am looking at this file: https://github.com/corelight/ecs-mapping/blob/master/automatic_install/corelight_ftp_pipeline

This includes, among others, things like this:

```json
        "rename": {
        "field": "command",
        "target_field": "ftp.command",
        "ignore_failure": true
      }
```

I could not find `ftp.command` in the official ECS definitions. Is this custom Corelight extension?

**Comment by hunter32me** [comment]
Correct FTP fields would be an extended field as ECS it seld does not have an ECS mapping for FTP. This is based on the Filebeats mappings of Zeek data.
