### ISSUE TITLE
Out-of-the-box Elasticsearch snags

### ISSUE THREAD

**Issue by philrz** [corelight/ecs-mapping#2]
For getting this working with open source Zeek, I happened to use an out-of-the-box Elasticsearch v7.4.0. I found a few places where the helper scripts clashed with this a bit.

1. [pipelines_import.sh](https://github.com/corelight/ecs-mapping/blob/master/automatic_install/pipelines_import.sh) has API usernames/passwords on all the `curl` command-lines, and from what I could tell, Elastic required setting `xpack.security.enabled: true` and running something like `bin/elasticsearch-setup-passwords` to set up credentials for the API users so I could enter those into the prompts when running `pipelines_import.sh`. It might be handy if the script had some kind of fallback mode where if username/password were not entered, it could attempt to access the API without credentials, since credential-free access is an out-of-the-box Elasticsearch default.

2. Similarly, the attempts to access the API via `https://` all failed in my out-of-the-box Elasticsearch config. I just did a search & replace to `http://` and that got it working. Maybe it would be good if the script attempted `https://` but then did an automatic fallback to trying `http://`.

3. If I ran [pipelines_import.sh](https://github.com/corelight/ecs-mapping/blob/master/automatic_install/pipelines_import.sh) and then quickly moved to ingest+index of my first event, I hit a circuit breaker:

```
{
	"error": {
		"root_cause": [{
			"type": "exception",
			"reason": "java.lang.IllegalArgumentException: GeneralScriptException[Failed to compile inline script [(ctx.conn_state == 'SF')] using lang [painless]]; nested: CircuitBreakingException[[script] Too many dynamic script compilations within, max: [75/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting];",
			"header": {
				"processor_type": "conditional"
			}
		}],
		"type": "exception",
		"reason": "java.lang.IllegalArgumentException: GeneralScriptException[Failed to compile inline script [(ctx.conn_state == 'SF')] using lang [painless]]; nested: CircuitBreakingException[[script] Too many dynamic script compilations within, max: [75/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting];",
		"caused_by": {
			"type": "illegal_argument_exception",
			"reason": "GeneralScriptException[Failed to compile inline script [(ctx.conn_state == 'SF')] using lang [painless]]; nested: CircuitBreakingException[[script] Too many dynamic script compilations within, max: [75/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting];",
			"caused_by": {
				"type": "general_script_exception",
				"reason": "Failed to compile inline script [(ctx.conn_state == 'SF')] using lang [painless]",
				"caused_by": {
					"type": "circuit_breaking_exception",
					"reason": "[script] Too many dynamic script compilations within, max: [75/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting",
					"bytes_wanted": 0,
					"bytes_limit": 0,
					"durability": "TRANSIENT"
				}
			}
		},
		"header": {
			"processor_type": "conditional"
		}
	},
	"status": 500
}
```

If I waited a few minutes, the condition passed and I no longer hit the circuit breaker. However, on future attempts, I just increased the limits by setting `script.max_compilations_rate: 5000/5m` in my `config/elasticsearch.yml`. I'm not sure if there's much you can do about this since I guess these conservative defaults in an out-of-the-box Elasticsearch config are there for a reason. But figured I'd mention it in case you want to document it as a possible snag,

**Comment by hunter32me** [comment]
The new version does have a cluster setting that changes the max_compilations rate. We also work to lower the number of scripts.
