### ISSUE TITLE
Any chance of getting updated mappings up to version v21

### ISSUE THREAD

**Issue by tvfischer** [corelight/ecs-mapping#20]
Version 21 introduced some new log files and update to some of the log files. Would it be possible to get an updated set of ingest pipeline definitions that map the new files?

**Comment by hunter32me** [comment]
This is something we are working on as well as updating to ECS 1.8 and new dashboards we are hoping to have it out soon. Thanks

**Comment by tvfischer** [comment]
Sounds good. Happy to beta test especially any new dashboards

**Comment by hunter32me** [comment]
V21 in Dev branch Will be posting new dashboards soon
