### ISSUE TITLE
tx_hosts and rx_hosts are mapped backwards

### ISSUE THREAD

**Issue by markoverholser** [corelight/ecs-mapping#21]
https://github.com/corelight/ecs-mapping/blob/e37f891ca2436fc1fe8118d92f3a0e897dc1dc62/automatic_install/corelight_files_pipeline#L21

These are flip-flopped. `tx_hosts` should be mapped to `source.ip` and `rx_hosts` should be mapped to `destination.ip`. If a client downloads a file from a server, the client is the rx_host and the server is the tx_host

**Comment by hunter32me** [comment]
Looking at adding files.source and files.destination to break from Layer 3 Source/Destination this should make this clearer for both upload and download who the sender is no matter who the source and destination from a Network level.

**Comment by hunter32me** [comment]
Update with new fields.
