### ISSUE TITLE
ecs-corelight-temporary-corelight_metrics_utilization-2021.08.10 incorrect "suricata" mapping.

### ISSUE THREAD

**Issue by Kytie** [corelight/ecs-mapping#31]
I am getting the following error from Logstash when trying to index the below data.
"object mapping for [suricata] tried to parse field [suricata] as object, but found a concrete value""
```json
{
    "ts": "2021-08-10T07:00:17Z",
    "_path": "corelight_metrics_utilization",
    "smartpcap": 0.0,
    "@timestamp": "2021-08-10T07:04:43.161Z",
    "@version": "1",
    "_system_name": "<REDACTED>",
    "sensor": 335389.2633333333,
    "suricata": 335389.2633333333,
    "_write_ts": "2021-08-10T07:00:17Z"
}
```
Looking at the mapping template that applies to this index, which seems to be the "template_corelight" template, we get the below mapping.

```json
"suricata" : {
  "properties" : {
    "metadata" : {
      "type" : "keyword",
      "fields" : {
        "text" : {
          "type" : "text"
        }
      }
    },
    "pcap_count" : {
      "type" : "long"
    }
  }
}
```

As you can see the mapping expects "suricata" to be an object but in a "corelight_metrics_utilization" log it appears to be a float.

**Comment by hunter32me** [comment]
Created new pipeline so it does not fall through to Temp new fields for utilization.corelight.<field name>
