### ISSUE TITLE
template_corelight_metrics_and_stats incorrect index pattern.

### ISSUE THREAD

**Issue by Kytie** [corelight/ecs-mapping#32]
The "template_corelight_metrics_and_stats" template has the below index pattern.

```json
"index_patterns": [
  "*corelight-zeek-metrics*",
  "*corelight-zeek-audit*",
  "*corelight-zeek-stats*",
  "*corelight-zeek-system*"
],
```
Looking at the naming convention that the indexnaming pipeline uses I don't think the above index pattern is correct and should be something like "zeek-corelight-metrics*", "zeek-corelight-audit*". I am unable to find any indexes created that have the above index pattern.

**Comment by hunter32me** [comment]
Fixed in latest push changed *corelight-zeek to zeek-corelight
