### ISSUE TITLE
Elasticsearch v8+ breaks type mapping.

### ISSUE THREAD

**Issue by Kytie** [corelight/ecs-mapping#38]
Received Error.

Trying to upload pipeline: template_corelight_parse_failures
URI = https://jst.es.eu-west-1.aws.found.io:9243/_template/template_corelight_parse_failures
{'error': {'root_cause': [{'type': 'mapper_parsing_exception', 'reason': 'Failed to parse mapping: dynamic template [string_fields] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"keyword","ignore_above":2048,"index":true,"norms":false,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string]'}], 'type': 'mapper_parsing_exception', 'reason': 'Failed to parse mapping: dynamic template [string_fields] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"keyword","ignore_above":2048,"index":true,"norms":false,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string]', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'dynamic template [string_fields] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"keyword","ignore_above":2048,"index":true,"norms":false,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string]', 'caused_by': {'type': 'mapper_parsing_exception', 'reason': 'unknown parameter [analyzer] on mapper [__dynamic__string_fields] of type [keyword]'}}}, 'status': 400}
{'error': {'root_cause': [{'type': 'mapper_parsing_exception', 'reason': 'Failed to parse mapping: dynamic template [string_fields] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"keyword","ignore_above":2048,"index":true,"norms":false,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string]'}], 'type': 'mapper_parsing_exception', 'reason': 'Failed to parse mapping: dynamic template [string_fields] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"keyword","ignore_above":2048,"index":true,"norms":false,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string]', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'dynamic template [string_fields] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"keyword","ignore_above":2048,"index":true,"norms":false,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string]', 'caused_by': {'type': 'mapper_parsing_exception', 'reason': 'unknown parameter [analyzer] on mapper [__dynamic__string_fields] of type [keyword]'}}}, 'status': 400}
{'error': {'root_cause': [{'type': 'mapper_parsing_exception', 'reason': 'Failed to parse mapping: dynamic template [string_fields] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"keyword","ignore_above":2048,"index":true,"norms":false,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string]'}], 'type': 'mapper_parsing_exception', 'reason': 'Failed to parse mapping: dynamic template [string_fields] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"keyword","ignore_above":2048,"index":true,"norms":false,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string]', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'dynamic template [string_fields] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"keyword","ignore_above":2048,"index":true,"norms":false,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string]', 'caused_by': {'type': 'mapper_parsing_exception', 'reason': 'unknown parameter [analyzer] on mapper [__dynamic__string_fields] of type [keyword]'}}}, 'status': 400}
{'error': {'root_cause': [{'type': 'mapper_parsing_exception', 'reason': 'Failed to parse mapping: dynamic template [string_fields] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"keyword","ignore_above":2048,"index":true,"norms":false,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string]'}], 'type': 'mapper_parsing_exception', 'reason': 'Failed to parse mapping: dynamic template [string_fields] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"keyword","ignore_above":2048,"index":true,"norms":false,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string]', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'dynamic template [string_fields] has invalid content [{"match_mapping_type":"string","mapping":{"analyzer":"keyword","ignore_above":2048,"index":true,"norms":false,"type":"keyword"}}], attempted to validate it with the following match_mapping_type: [string]', 'caused_by': {'type': 'mapper_parsing_exception', 'reason': 'unknown parameter [analyzer] on mapper [__dynamic__string_fields] of type [keyword]'}}}, 'status': 400}

This error does not appear on Elasticsearch 7.17.

Here is an article I found on this issue.

https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

**Comment by hunter32me** [comment]
Corelight ECS has been broken out into a few three different parts, ECS mappings has all the ingest piplines, there are ECS templates and logstash pipelines. WIth v8 you will need to us component templates that are kept in the ecs-templates project you will see logstash and ingest templates there.
